site_name: Calculinux Documentation
site_description: Documentation for Calculinux - A Linux distribution for PicoCalc with Luckfox Lyra and similar SBCs
site_author: Calculinux Project
site_url: https://docs.calculinux.org/

repo_name: Calculinux/meta-calculinux
repo_url: https://github.com/Calculinux/meta-calculinux
edit_uri: https://github.com/Calculinux/docs/edit/main/docs/

theme:
  name: material
  #custom_dir: overrides
  logo: assets/calculinux.svg
  favicon: assets/calculinux.png
  palette:
    # Dark mode (default)
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit

extra_css:
  - stylesheets/flatly.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - Home: index.md
  
  - Getting Started:
    - Overview: getting-started/overview.md
    - Hardware Requirements: getting-started/hardware-requirements.md
    - Installation: getting-started/installation.md
    - First Boot: getting-started/first-boot.md
    - Quick Start Guide: getting-started/quick-start.md
  
  - Hardware:
    - PicoCalc Overview: hardware/picocalc.md
    - Luckfox Lyra: hardware/luckfox-lyra.md
    - Technical Specifications: hardware/specifications.md
    - Hardware Modifications: hardware/modifications.md
    - Display & Input: hardware/display-input.md
    - Compatibility Matrix: hardware/compatibility.md
  
  - User Guide:
    - Package Management: user-guide/package-management.md
  
  - Developer Guide:
    - Development Overview: developer/overview.md
    - Setting Up Yocto: developer/yocto-setup.md
    - Building Calculinux: developer/building.md
    - Contributing: developer/contributing.md
  
  - Troubleshooting:
    - Common Issues: troubleshooting/common-issues.md
    - Boot Problems: troubleshooting/boot-problems.md
    - Display Issues: troubleshooting/display.md
    - Input Problems: troubleshooting/input.md
    - Network Issues: troubleshooting/network.md
    - Erasing SPI NAND: troubleshooting/erase-nand.md
    - FAQ: troubleshooting/faq.md
  
  - Resources:
    - Community Links: resources/community.md
    - External Documentation: resources/external-docs.md
